-- QooERP 文件服务模块数据库初始化脚本

-- 文件信息表
CREATE TABLE IF NOT EXISTS file_info (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  file_no VARCHAR(50) NOT NULL,
  file_name VARCHAR(200) NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  file_size BIGINT NOT NULL,
  file_type VARCHAR(100),
  file_extension VARCHAR(20),
  file_md5 VARCHAR(64),
  storage_type VARCHAR(20) DEFAULT 'minio',
  folder_id BIGINT,
  status SMALLINT DEFAULT 1,
  download_count INTEGER DEFAULT 0,
  tenant_id BIGINT NOT NULL,
  creator_id BIGINT NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater_id BIGINT,
  update_time TIMESTAMP,
  deleted SMALLINT DEFAULT 0
);

CREATE INDEX idx_file_info_folder_id ON file_info(folder_id);
CREATE INDEX idx_file_info_file_md5 ON file_info(file_md5);
CREATE INDEX idx_file_info_tenant_id ON file_info(tenant_id);
CREATE INDEX idx_file_info_creator_id ON file_info(creator_id);
CREATE INDEX idx_file_info_create_time ON file_info(create_time);

-- 文件夹表
CREATE TABLE IF NOT EXISTS file_folder (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  folder_no VARCHAR(50) NOT NULL,
  folder_name VARCHAR(100) NOT NULL,
  parent_id BIGINT DEFAULT 0,
  folder_path VARCHAR(500),
  folder_level INTEGER DEFAULT 1,
  sort INTEGER DEFAULT 0,
  status SMALLINT DEFAULT 1,
  tenant_id BIGINT NOT NULL,
  creator_id BIGINT NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater_id BIGINT,
  update_time TIMESTAMP,
  deleted SMALLINT DEFAULT 0
);

CREATE INDEX idx_file_folder_parent_id ON file_folder(parent_id);
CREATE INDEX idx_file_folder_tenant_id ON file_folder(tenant_id);
CREATE INDEX idx_file_folder_creator_id ON file_folder(creator_id);

-- 文件分享表
CREATE TABLE IF NOT EXISTS file_share (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  file_id BIGINT NOT NULL,
  share_code VARCHAR(50) NOT NULL,
  share_password VARCHAR(100),
  share_name VARCHAR(200),
  share_desc VARCHAR(500),
  expire_time TIMESTAMP,
  visit_count INTEGER DEFAULT 0,
  download_count INTEGER DEFAULT 0,
  status SMALLINT DEFAULT 1,
  tenant_id BIGINT NOT NULL,
  creator_id BIGINT NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted SMALLINT DEFAULT 0
);

CREATE UNIQUE INDEX uk_file_share_code ON file_share(share_code);
CREATE INDEX idx_file_share_file_id ON file_share(file_id);
CREATE INDEX idx_file_share_tenant_id ON file_share(tenant_id);
CREATE INDEX idx_file_share_creator_id ON file_share(creator_id);
CREATE INDEX idx_file_share_expire_time ON file_share(expire_time);

-- 文件操作日志表
CREATE TABLE IF NOT EXISTS file_log (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  file_id BIGINT,
  operation VARCHAR(50) NOT NULL,
  operation_desc VARCHAR(500),
  operator_id BIGINT NOT NULL,
  operator_name VARCHAR(100),
  operator_ip VARCHAR(50),
  user_agent VARCHAR(500),
  operation_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tenant_id BIGINT NOT NULL
);

CREATE INDEX idx_file_log_file_id ON file_log(file_id);
CREATE INDEX idx_file_log_operator_id ON file_log(operator_id);
CREATE INDEX idx_file_log_operation_time ON file_log(operation_time);
CREATE INDEX idx_file_log_tenant_id ON file_log(tenant_id);

-- 存储配额表
CREATE TABLE IF NOT EXISTS file_quota (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tenant_id BIGINT NOT NULL UNIQUE,
  total_quota BIGINT DEFAULT 107374182400,
  used_quota BIGINT DEFAULT 0,
  file_count INTEGER DEFAULT 0,
  folder_count INTEGER DEFAULT 0,
  last_calculate_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 初始化默认租户配额
INSERT INTO file_quota (tenant_id, total_quota, used_quota, file_count, folder_count)
VALUES (1, 107374182400, 0, 0, 0)
ON CONFLICT (tenant_id) DO NOTHING;
